psu23/youjuke

- assets/css/style.css
- index.html
> added initial html layout

- assets/css/style.css
- assets/javascript/app.js
- index.html
> Gsa music player

- assets/css/style.css
- assets/javascript/app.js
- assets/njtest/package-lock.json
- assets/njtest/server.js
- index.html
Can now add songs from a search to the queue, and thought of new way of keeping track of songs is by their deezer id which can be saved as a data attributes. No styling put into considering yet, just wanted to see if the code worked!
> Psu search and add to queue

- assets/css/style.css
- assets/javascript/app.js
Set up the playlist to play automatically
> songs in playlist now play consecutively

- assets/javascript/app.js
I set up the query to pull lyrics based on the song index. Needs troubleshooting because the response for the lyrics does not come back in JSON format. So I'm having trouble pulling just the lyrics from the response.
> set up query for lyrics and put them on the page

- assets/css/style.css
- assets/javascript/app.js
- index.html
Fixed playlist load issue by loading playlist from "playlist" variable. Also synchronized loading of lyrics when a new song starts.
> Gsa synchronize fixes

- assets/css/style.css
- assets/javascript/app.js
- index.html
Finally figured out how to get lyrics! Just needed extra input in the ajax call, including having to specify jsonp format and callback.
I also realized that the initial playlist is in random order upon each page reload because ajax is asynchronous and completes functions for each variable in order of how quickly the data can be obtained for each call. For now, I set ' "async": false ' for renderQueue(), so that it runs ajax one input at a time (in the order of the array), but apparently this isn't the best practice because it can make page loading seem laggy and isn't great for user experience. Let's keep that in mind and I'll try to figure out better ways of using ajax in a way that can pull data asynchronously, but append the output in the proper order (in the order of the array)
> changed async to false to render playlist in proper order, got lyrics

- assets/css/style.css
- assets/javascript/app.js
- index.html
Changes so that lyrics div appears only after a song is played, and did some temporary overflow fixes so lyrics don't span beyond container, will tidy up later
> added some overflow scrolling

- assets/javascript/app.js
- index.html
> updated renderqueue function to display current song on page

- assets/javascript/app.js
> added classes to vote buttons

- assets/css/style.css
- assets/javascript/app.js
- index.html
> added start listening button to play and pause song

- assets/css/style.css
- assets/javascript/app.js
- index.html
> cleaned up playlist layout

- assets/css/style.css
- assets/javascript/app.js
cleaned up search results layout
> cleaned up search results layout

- assets/css/style.css
- assets/javascript/app.js
- index.html
> made little improvements to layout

- assets/javascript/app.js
Got vote buttons to keep track of score, considering only keeping voteup as a way of keep track of both up- and downvoting.
Bubble sorting (commented out in the last lines) having some issues with recognizing playlist[i].upvote (or arr[i].upvote as defined in the function). Also commented out calls to the sortPlaylist() function in # song.on(ended) (as well as a playedTracks array that finished songs get pushed to and shift()'ed out of the array (shift() function takes out the first element out of an array).
> buttons now keep track of score but sorting not yet sorted out

- assets/css/style.css
- assets/javascript/app.js
- index.html
Added live search as you type and X button to clear results
> improved search functionality

- assets/javascript/app.js
> updated sort playlist function

- assets/css/style.css
- assets/javascript/app.js
- index.html
> added modal when a new song is added to playlist

- assets/css/style.css
- assets/javascript/app.js
- index.html
> added sign-in modal

- assets/css/style.css
- assets/javascript/app.js
- index.html
Working on a lot more including new buttons and "animations" for buttons that Materialize provides, as well as fixing other layout issues including scrolling and overflow etc. But just wanted to give this updated layout with sticky header so that we're on the same page with changes! I will work more on the layout tonight and tomorrow
> new layout

- assets/css/style.css
- assets/javascript/app.js
- index.html
Code works now, added some mobile responsiveness. Will do a lot more work on styling
> Psu updated layout 2

- assets/css/style.css
- assets/javascript/app.js
- index.html
Had to adjust header layout to allow sign-in modal to work.
> adjusted layout in header so that sign-in modal works

- assets/css/style.css
- index.html
This was a great idea by you! Love how this keeps the page looking a lot cleaner
> added nav for middle section

- assets/css/style.css
- assets/javascript/app.js
- index.html
Just made some changes to column sizes, fixed some overflow issues, going to continue editing the layout and features
> Psu layout container sizes

- assets/javascript/app.js
> fixed end of playlist issue

- assets/css/style.css
- index.html
Added some more mobile responsiveness and fixing layout issues (continuing html/css layout changes). This branch doesn't have the new js you put in to fix the end of playlist issues yet so be careful when merging!
> added some more mobile responsiveness and layout issues

- assets/javascript/app.js
- index.html
Chart that shows current user music preferences
> added chart to info tab

- assets/css/style.css
- index.html
Layout now has mobile responsiveness with the listening chart, will continue working on layout and add some Materialize elements later
> Psu mobile resp w chart

- assets/css/style.css
- assets/javascript/app.js
- index.html
Added materialize buttons. Will explore more abilities of materialize and continue editing the layout/font size
> Psu materialize buttons

- assets/javascript/app.js
> fixed duplicating issue when choosing new song

- assets/css/style.css
- index.html
Made some changes to the layout, added icons, temporarily removed chat panel, tweaked text and element alignment
> Psu layout proportion fix

- assets/css/style.css
Previous push had error where modal would show a song was added, but the song did not show up in the queue. I think I fixed it here
> Psu scrollbar

- assets/css/style.css
Realized looking at the app in landscape on mobile caused the sticky header to take up 2/3 of the screen so I changed it to static
> removed sticky header for mobile

- assets/css/style.css
- assets/javascript/app.js
- index.html
> Psu most liked songs

- assets/css/style.css
- assets/javascript/app.js
- index.html
Updated the rankings tab with artwork, changed some styling. Each tab now has a fixed height (like the queue and search tabs did) so that when a user clicks on a tab in mobile view the content is not empty for the tabs where information was not yet appended to that tab.
> Psu fixed container sizes

- assets/css/style.css
- assets/javascript/app.js
- index.html
Went through the css list and fixed some issues. For the coloring of buttons, I left some other options cleared out in case you don't like the color I changed. Also added stuff to the info tab, feel free to edit it!
> Psu css tweaks

- assets/javascript/app.js
- index.html
Username gets saved in local storage, but can't get it to appear in the name box after reload. If another div is targeted, like .chat-container for example, the username will appear there after page reload. Maybe getItem doesn't allow you to print saved variables in 'input' fields? The function works and saves the username in local storage however
> username gets saved in local storage

- assets/css/style.css
- assets/javascript/app.js
- index.html
Major header css revisions for play pause button to appear in the player, fixed graph scaling issue, left commented-out lines for possible localStorage for sign-in button
> Psu css tweaks 2

- assets/javascript/app-test.js
- assets/javascript/app.js
- index.html
Sorting is still a little glitchy but should be simple fixes.
> Gsa beta good

- assets/javascript/app.js
Rather than stop and restart upon re-clicking the play/pause button, which I've noticed has been happening for the past several pushes.
> commenting out line 290 in app.js allows the song to pause

- assets/css/style.css
- assets/javascript/app.js
- index.html
Added volume bar, changes can also be applied to master-beta version
> added volume bar

- assets/css/style.css
- assets/javascript/app.js
- index.html
Firebase version, want to add to master/firebase version. also added volume and changed some styling
> added volume to firebase version

- assets/css/style.css
- assets/javascript/app.js
- index.html
> re-organized and added comments to javascript

- assets/css/style.css
> change the background color of the volume slider
